SciO Scheduler 2/Controllers/GanttsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SciO_Scheduler_2.Data;
using SciO_Scheduler_2.Models;

namespace SciO_Scheduler_2.Controllers
{
    public class GanttsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GanttsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Gantts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Gantt.ToListAsync());
        }

        // GET: Gantts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gantt = await _context.Gantt
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gantt == null)
            {
                return NotFound();
            }

            return View(gantt);
        }

        // GET: Gantts/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: Gantts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,studentName,studentLastName,studentEvents,email")] Gantt gantt)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gantt);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gantt);
        }

        // GET: Gantts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gantt = await _context.Gantt.FindAsync(id);
            if (gantt == null)
            {
                return NotFound();
            }
            return View(gantt);
        }

        // POST: Gantts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,studentName,studentLastName,studentEventsA,studentEventsB,studentEventsC,studentEventsD,studentEventsE,studentEventsF, studentEventsSelf,email")] Gantt gantt)
        {
            if (id != gantt.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gantt);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GanttExists(gantt.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gantt);
        }

        // GET: Gantts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gantt = await _context.Gantt
                .FirstOrDefaultAsync(m => m.Id == id);
            if (gantt == null)
            {
                return NotFound();
            }

            return View(gantt);
        }

        // POST: Gantts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gantt = await _context.Gantt.FindAsync(id);
            _context.Gantt.Remove(gantt);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GanttExists(int id)
        {
            return _context.Gantt.Any(e => e.Id == id);
        }
    }
}

SciO Scheduler 2/Controllers/timeTablesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SciO_Scheduler_2.Data;
using SciO_Scheduler_2.Models;

namespace SciO_Scheduler_2.Controllers
{
    public class timeTablesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public timeTablesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: timeTables
        public async Task<IActionResult> Index()
        {
            return View(await _context.timeTable.ToListAsync());
        }

        // GET: timeTables/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeTable = await _context.timeTable
                .FirstOrDefaultAsync(m => m.venue == id);
            if (timeTable == null)
            {
                return NotFound();
            }

            return View(timeTable);
        }

        // GET: timeTables/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: timeTables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("venue,blockAStartTime,blockAEndTime,blockBStartTime,blockBEndTime,blockCStartTime,blockCEndTime,blockDStartTime,blockDEndTime,blockEStartTime,blockEEndTime,blockFStartTime,blockFEndTime,bridgesStartTime,bridgesEndTime,gravityVehicleStartTime,gravityVehicleEndTime,pingPongParachuteStartTime,pingPongParachuteEndTime,trajectoryStartTime,trajectoryEndTime,wrightStuffStartTime,wrightStuffEndTime")] timeTable timeTable)
        {
            if (ModelState.IsValid)
            {
                _context.Add(timeTable);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(timeTable);
        }

        // GET: timeTables/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeTable = await _context.timeTable.FindAsync(id);
            if (timeTable == null)
            {
                return NotFound();
            }
            return View(timeTable);
        }

        // POST: timeTables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("venue,blockAStartTime,blockAEndTime,blockBStartTime,blockBEndTime,blockCStartTime,blockCEndTime,blockDStartTime,blockDEndTime,blockEStartTime,blockEEndTime,blockFStartTime,blockFEndTime,bridgesStartTime,bridgesEndTime,gravityVehicleStartTime,gravityVehicleEndTime,pingPongParachuteStartTime,pingPongParachuteEndTime,trajectoryStartTime,trajectoryEndTime,wrightStuffStartTime,wrightStuffEndTime")] timeTable timeTable)
        {
            if (id != timeTable.venue)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(timeTable);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!timeTableExists(timeTable.venue))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(timeTable);
        }

        // GET: timeTables/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timeTable = await _context.timeTable
                .FirstOrDefaultAsync(m => m.venue == id);
            if (timeTable == null)
            {
                return NotFound();
            }

            return View(timeTable);
        }

        // POST: timeTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var timeTable = await _context.timeTable.FindAsync(id);
            _context.timeTable.Remove(timeTable);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool timeTableExists(string id)
        {
            return _context.timeTable.Any(e => e.venue == id);
        }
    }
}

SciO Scheduler 2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SciO_Scheduler_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SciO_Scheduler_2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SciO_Scheduler_2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Events">Events</a>
                        </li>
                        <!--<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Gantt">Gantt</a>
                        </li>-->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gantts" asp-action="Index">Gantt</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MyChart">Chart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="timeTables" asp-action="Index">Time Table</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SciO_Scheduler_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>